remote_theme: mmistakes/minimal-mistakes
title: Mohammad Al-Rammah
description: "Code, projects, and things I've built along the way."
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      header:
        overlay_color: "#000"
